export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_CURRENT_ACTICLE_PAGE = 'SET_CURRENT_ACTICLE_PAGE';
export const SET_IS_FETCHING = 'SET_IS_FETCHING';
export const SET_LOGIN_USER = 'SET_LOGIN_USER';
export const SET_IMG_LOGIN_USER = 'SET_IMG_LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
